### ISSUE TITLE
File open dialog is not the accurate one (See Roblox 07 v488)

### ISSUE THREAD

**Issue by Lannuked** [Vulpovile/Blocks3D#36]

**Comment by Vulpovile** [comment]
So I tried getting it to use the old places dialog, but then it just crashed. I'm not entirely sure how I'd let it use the older XP style dialog.

**Comment by NTx86** [comment]
I think we should use the newer dialog because the old one is really bad.

**Comment by Vulpovile** [comment]
It's horrible, but it's accurate.

I wonder if we need platform SDK for windows XP or 2000 for this

**Comment by ghost** [comment]
use windows 3.X one

**Comment by Vulpovile** [comment]
Nah man, it has to be Windows 1.x or nothing

**Comment by brannanz** [comment]
Super late, but I'm sure that ROBLOX never actually coded the file dialog init stuff. They used MFC by 2007, which by default uses the places dialog.

**Comment by Vulpovile** [comment]
That's a really good point. We don't really know if ROBLOX used MFC at this point (probably), and since we're stuck without it, we might as well close this, at least for now
